language: android
android:
  components:
    - tools
    # The SDK version used to compile your project
    - android-26
    # The BuildTools version used by your project
    - build-tools-26.0.0

    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.m2/repository

script: ./gradlew build

before_deploy: ./before_deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    tags: true
